#pragma once

// =====================================================================
// Edge AI model
// =====================================================================
//
// Generated by running the project's own ai_training/generate_dataset.py
// and ai_training/train_models.py (SRS Section 9.5) - these are REAL
// trained coefficients, not placeholders.
//
// Training configuration:
//   Dataset size : 8,000 rows (generate_dataset.py, seed 42)
//   Train/test   : 80/20 split, random_state 42
//
// Measured performance (see ai_training/model_metrics.txt):
//   Arrival model  : Logistic Regression, test accuracy = 0.8888
//   Duration model : Linear Regression,   test R^2 = 0.6421, MAE = 13.99 min
//
// Feature order follows SRS Section 8.6.2 / train_models.py FEATURES:
//
//   1. hourOfDay
//   2. dayOfWeek
//   3. bayOccupied
//   4. recentAvgCurrent
//   5. sessionElapsedMin
//   6. neighborBaysOccupied
//   7. historicalArrivalRate
//
// Both models are implemented as plain C/C++ arithmetic (equivalent to
// m2cgen output) so no TensorFlow / tree-class runtime is required on
// the ESP32.
// =====================================================================

#include <math.h>

// =====================================================================
// Arrival probability model (Logistic Regression)
// =====================================================================

static inline float predictArrival(
    float hourOfDay,
    float dayOfWeek,
    float bayOccupied,
    float recentAvgCurrent,
    float sessionElapsedMin,
    float neighborBaysOccupied,
    float historicalArrivalRate)
{
    float raw =
        -2.36279781395152f

        + (-0.0028288418793823624f * hourOfDay)

        + (-0.02420439758631001f * dayOfWeek)

        + (-0.2968811975491676f * bayOccupied)

        + (-0.02175315800642946f * recentAvgCurrent)

        + (0.001990310809964769f * sessionElapsedMin)

        + (-0.09148054117779326f * neighborBaysOccupied)

        + (2.1045872896575513f * historicalArrivalRate);

    // Prevent numerical overflow in expf().
    if (raw > 20.0f)
    {
        raw = 20.0f;
    }

    if (raw < -20.0f)
    {
        raw = -20.0f;
    }

    float probability =
        1.0f /
        (1.0f + expf(-raw));

    if (probability < 0.0f)
    {
        probability = 0.0f;
    }

    if (probability > 1.0f)
    {
        probability = 1.0f;
    }

    return probability;
}

// =====================================================================
// Session duration model (Linear Regression)
// =====================================================================

static inline float predictDuration(
    float hourOfDay,
    float dayOfWeek,
    float bayOccupied,
    float recentAvgCurrent,
    float sessionElapsedMin,
    float neighborBaysOccupied,
    float historicalArrivalRate)
{
    float duration =
        151.65592670255637f

        + (-0.05798128967930472f * hourOfDay)

        + (0.11607861873512368f * dayOfWeek)

        + (0.0f * bayOccupied)

        + (-1.832886566126963f * recentAvgCurrent)

        + (-0.4507540454621482f * sessionElapsedMin)

        + (0.02990699452609528f * neighborBaysOccupied)

        + (2.938165472166577f * historicalArrivalRate);

    // Keep the output within a practical session range.
    if (duration < 0.0f)
    {
        duration = 0.0f;
    }

    if (duration > 240.0f)
    {
        duration = 240.0f;
    }

    return duration;
}
